// <auto-generated />
using System;
using CarRepairShop.Areas.Identity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRepairShop.Migrations
{
    [DbContext(typeof(MEchanicDataContext))]
    [Migration("20230402190211_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarRepairShop.Areas.Identity.Data.Mechanic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CarRepairShop.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"), 1L, 1);

                    b.Property<int>("CarBrand")
                        .HasColumnType("int");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarRegistration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EngineNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrameNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerPhoneNum")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<double>("WorkingVolume")
                        .HasColumnType("float");

                    b.Property<int>("YearOfManifacture")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarRepairShop.Models.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"), 1L, 1);

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfRepair")
                        .HasColumnType("int");

                    b.Property<int>("WorkingHours")
                        .HasColumnType("int");

                    b.HasKey("PartId");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            PartId = 1,
                            PartName = "Engine block",
                            Price = 2000m,
                            Quantity = 10,
                            TypeOfRepair = 1,
                            WorkingHours = 8
                        },
                        new
                        {
                            PartId = 2,
                            PartName = "Oil filer",
                            Price = 35m,
                            Quantity = 10,
                            TypeOfRepair = 1,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 3,
                            PartName = "Oil pump",
                            Price = 45m,
                            Quantity = 10,
                            TypeOfRepair = 1,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 4,
                            PartName = "Serpentine belt",
                            Price = 20m,
                            Quantity = 10,
                            TypeOfRepair = 1,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 5,
                            PartName = "Water pump",
                            Price = 40m,
                            Quantity = 10,
                            TypeOfRepair = 2,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 6,
                            PartName = "Radiator",
                            Price = 50m,
                            Quantity = 10,
                            TypeOfRepair = 2,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 7,
                            PartName = "Coolong fan",
                            Price = 42m,
                            Quantity = 10,
                            TypeOfRepair = 2,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 8,
                            PartName = "Catalytic converter",
                            Price = 170m,
                            Quantity = 10,
                            TypeOfRepair = 3,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 9,
                            PartName = "Muffler",
                            Price = 40m,
                            Quantity = 10,
                            TypeOfRepair = 3,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 10,
                            PartName = "Exhaust pipe",
                            Price = 18m,
                            Quantity = 10,
                            TypeOfRepair = 3,
                            WorkingHours = 4
                        },
                        new
                        {
                            PartId = 11,
                            PartName = "Fuel pump",
                            Price = 63m,
                            Quantity = 10,
                            TypeOfRepair = 4,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 12,
                            PartName = "Fuel filter",
                            Price = 57m,
                            Quantity = 10,
                            TypeOfRepair = 4,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 13,
                            PartName = "Fuel tank",
                            Price = 200m,
                            Quantity = 10,
                            TypeOfRepair = 4,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 14,
                            PartName = "Wiring and cables",
                            Price = 12m,
                            Quantity = 10,
                            TypeOfRepair = 5,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 15,
                            PartName = "Starter",
                            Price = 56m,
                            Quantity = 10,
                            TypeOfRepair = 5,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 16,
                            PartName = "Battery",
                            Price = 48m,
                            Quantity = 10,
                            TypeOfRepair = 5,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 17,
                            PartName = "Control buttons",
                            Price = 10m,
                            Quantity = 10,
                            TypeOfRepair = 5,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 18,
                            PartName = "Brake rotors",
                            Price = 60m,
                            Quantity = 10,
                            TypeOfRepair = 6,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 19,
                            PartName = "ABS system parts",
                            Price = 39m,
                            Quantity = 10,
                            TypeOfRepair = 6,
                            WorkingHours = 2
                        },
                        new
                        {
                            PartId = 20,
                            PartName = "Braking plate",
                            Price = 28m,
                            Quantity = 10,
                            TypeOfRepair = 6,
                            WorkingHours = 3
                        });
                });

            modelBuilder.Entity("CarRepairShop.Models.RepairCard", b =>
                {
                    b.Property<int>("RepairCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepairCardId"), 1L, 1);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MechanicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeOfRepair")
                        .HasColumnType("int");

                    b.HasKey("RepairCardId");

                    b.HasIndex("CarId");

                    b.HasIndex("MechanicId");

                    b.ToTable("Repair_Cards");
                });

            modelBuilder.Entity("CarRepairShop.Models.Town", b =>
                {
                    b.Property<int>("TownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TownId"), 1L, 1);

                    b.Property<string>("TownCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TownId");

                    b.ToTable("Towns");

                    b.HasData(
                        new
                        {
                            TownId = 1,
                            TownCode = "E"
                        },
                        new
                        {
                            TownId = 2,
                            TownCode = "A"
                        },
                        new
                        {
                            TownId = 3,
                            TownCode = "B"
                        },
                        new
                        {
                            TownId = 4,
                            TownCode = "BT"
                        },
                        new
                        {
                            TownId = 5,
                            TownCode = "BH"
                        },
                        new
                        {
                            TownId = 6,
                            TownCode = "BP"
                        },
                        new
                        {
                            TownId = 7,
                            TownCode = "EB"
                        },
                        new
                        {
                            TownId = 8,
                            TownCode = "TX"
                        },
                        new
                        {
                            TownId = 9,
                            TownCode = "K"
                        },
                        new
                        {
                            TownId = 10,
                            TownCode = "KH"
                        },
                        new
                        {
                            TownId = 11,
                            TownCode = "OB"
                        },
                        new
                        {
                            TownId = 12,
                            TownCode = "M"
                        },
                        new
                        {
                            TownId = 13,
                            TownCode = "PA"
                        },
                        new
                        {
                            TownId = 14,
                            TownCode = "PK"
                        },
                        new
                        {
                            TownId = 15,
                            TownCode = "EH"
                        },
                        new
                        {
                            TownId = 16,
                            TownCode = "PB"
                        },
                        new
                        {
                            TownId = 17,
                            TownCode = "PP"
                        },
                        new
                        {
                            TownId = 18,
                            TownCode = "P"
                        },
                        new
                        {
                            TownId = 19,
                            TownCode = "CC"
                        },
                        new
                        {
                            TownId = 20,
                            TownCode = "CH"
                        },
                        new
                        {
                            TownId = 21,
                            TownCode = "CM"
                        },
                        new
                        {
                            TownId = 22,
                            TownCode = "CO"
                        },
                        new
                        {
                            TownId = 23,
                            TownCode = "CA"
                        },
                        new
                        {
                            TownId = 24,
                            TownCode = "CB"
                        },
                        new
                        {
                            TownId = 25,
                            TownCode = "CT"
                        },
                        new
                        {
                            TownId = 26,
                            TownCode = "T"
                        },
                        new
                        {
                            TownId = 27,
                            TownCode = "X"
                        },
                        new
                        {
                            TownId = 28,
                            TownCode = "H"
                        },
                        new
                        {
                            TownId = 29,
                            TownCode = "Y"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PartRepairCard", b =>
                {
                    b.Property<int>("PartsPartId")
                        .HasColumnType("int");

                    b.Property<int>("RepairCardsRepairCardId")
                        .HasColumnType("int");

                    b.HasKey("PartsPartId", "RepairCardsRepairCardId");

                    b.HasIndex("RepairCardsRepairCardId");

                    b.ToTable("RepairCardParts", (string)null);
                });

            modelBuilder.Entity("CarRepairShop.Models.RepairCard", b =>
                {
                    b.HasOne("CarRepairShop.Models.Car", "Car")
                        .WithMany("RepairCards")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRepairShop.Areas.Identity.Data.Mechanic", "Mechanic")
                        .WithMany("RepairCards")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Mechanic");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CarRepairShop.Areas.Identity.Data.Mechanic", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CarRepairShop.Areas.Identity.Data.Mechanic", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRepairShop.Areas.Identity.Data.Mechanic", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CarRepairShop.Areas.Identity.Data.Mechanic", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartRepairCard", b =>
                {
                    b.HasOne("CarRepairShop.Models.Part", null)
                        .WithMany()
                        .HasForeignKey("PartsPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRepairShop.Models.RepairCard", null)
                        .WithMany()
                        .HasForeignKey("RepairCardsRepairCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarRepairShop.Areas.Identity.Data.Mechanic", b =>
                {
                    b.Navigation("RepairCards");
                });

            modelBuilder.Entity("CarRepairShop.Models.Car", b =>
                {
                    b.Navigation("RepairCards");
                });
#pragma warning restore 612, 618
        }
    }
}
